import type { Event, Venue } from './types';

export const venues: Venue[] = [
  { id: 'v1', name: 'Théâtre Régional de Mostaganem', address: 'Rue de la Révolution, Mostaganem', lat: 35.9333, lng: 0.0894 },
  { id: 'v2', name: 'Plage de Sidi Mejdoub', address: 'Sidi Mejdoub, Mostaganem', lat: 35.9602, lng: 0.0573 },
  { id: 'v3', name: 'Jardin Emir Abdelkader', address: 'Centre Ville, Mostaganem', lat: 35.9310, lng: 0.0880 },
  { id: 'v4', name: 'Complexe Sportif de Mostaganem', address: 'Route d\'Oran, Mostaganem', lat: 35.9123, lng: 0.1012 },
  { id: 'v5', name: 'Esplanade de la Salamandre', address: 'La Salamandre, Mostaganem', lat: 35.9385, lng: 0.0768 },
];

export const events: Event[] = [
  {
    id: 'e1',
    name: 'Festival de Musique Andalouse',
    date: '2024-08-15',
    time: '20:00',
    location: 'Théâtre Régional de Mostaganem',
    description: 'Une soirée enchanteresse avec les plus grands noms de la musique andalouse.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'orchestra music',
    category: 'Music',
    venueId: 'v1',
  },
  {
    id: 'e2',
    name: 'Exposition d\'Art "Couleurs de Mosta"',
    date: '2024-08-20',
    time: '10:00 - 18:00',
    location: 'Jardin Emir Abdelkader',
    description: 'Découvrez les œuvres d\'artistes locaux inspirés par la beauté de la région.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'art gallery',
    category: 'Art',
    venueId: 'v3',
  },
  {
    id: 'e3',
    name: 'Fête de la Sardine',
    date: '2024-08-25',
    time: '12:00 - 22:00',
    location: 'Esplanade de la Salamandre',
    description: 'Dégustation de sardines grillées, animations et musique au bord de la mer.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'grilled fish',
    category: 'Food',
    venueId: 'v5',
  },
  {
    id: 'e4',
    name: 'Tournoi de Beach Volley',
    date: '2024-09-01',
    time: '09:00',
    location: 'Plage de Sidi Mejdoub',
    description: 'Compétition amicale de beach-volley ouverte à tous les niveaux.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'beach volleyball',
    category: 'Sports',
    venueId: 'v2',
  },
  {
    id: 'e5',
    name: 'Journée du Patrimoine Culturel',
    date: '2024-09-10',
    time: '10:00 - 17:00',
    location: 'Théâtre Régional de Mostaganem',
    description: 'Visites guidées et conférences sur l\'histoire riche de Mostaganem.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'historic building',
    category: 'Culture',
    venueId: 'v1',
  },
  {
    id: 'e6',
    name: 'Concert de Raï en plein air',
    date: '2024-09-15',
    time: '21:00',
    location: 'Complexe Sportif de Mostaganem',
    description: 'Vibrez au son du Raï avec des stars nationales.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'music concert',
    category: 'Music',
    venueId: 'v4'
  },
  {
    id: 'e7',
    name: 'Salon du Livre de Mostaganem',
    date: '2024-10-05',
    time: '09:00 - 19:00',
    location: 'Jardin Emir Abdelkader',
    description: 'Rencontrez des auteurs et découvrez les dernières parutions littéraires.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'book fair',
    category: 'Culture',
    venueId: 'v3'
  },
  {
    id: 'e8',
    name: 'Marathon de la Corniche',
    date: '2024-10-20',
    time: '08:00',
    location: 'Esplanade de la Salamandre',
    description: 'Courez le long de la magnifique côte de Mostaganem.',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'marathon running',
    category: 'Sports',
    venueId: 'v5'
  }
];
