

import { PageHeader } from '@/components/page-header';
import { PersonalizedSuggestionsClient } from '@/components/personalized-suggestions-client';

export default function SuggestionsPage() {
  return (
    <div className="space-y-8">
      <PageHeader
        title="Suggestions For You"
        description="Personalized routes and points of interest, generated by AI based on your preferences and activity."
      />
      <PersonalizedSuggestionsClient />
    </div>
  );
}
